### ISSUE TITLE
Only one camera work at a time

### ISSUE THREAD

**Issue by oh6fub** [pikvm/ustreamer#99] opened 2021-03-14 17:53 UTC
I have tested mjpg-streamer with four (4) webcameras (Live! Cam Sync 1080p) and apart from limitations and issues with mjpg-streamer, I can all of them stream simultaneously on Raspberry Pi 4.

However, with ustreamer I can only get one work at a time. Next camera will just stay in infinite loop, waiting for something eternally:

-- DEBUG [5590.448    stream] -- Waiting for worker ...
-- DEBUG [5590.448    stream] -- Calling select() on video device ...
-- DEBUG [5590.448      jw-0] -- Hello! I am a worker jw-0 ^_^
-- DEBUG [5590.448      jw-0] -- Worker jw-0 waiting for a new job ...
-- DEBUG [5591.456      http] -- HTTP: Repeating exposed ...
-- DEBUG [5592.461      http] -- HTTP: Repeating exposed ...
-- DEBUG [5593.471      http] -- HTTP: Repeating exposed ...
-- DEBUG [5594.493      http] -- HTTP: Repeating exposed ...
-- DEBUG [5595.453    stream] -- Device select() --> 0
-- ERROR [5595.453    stream] -- Mainloop select() error: Success
-- INFO  [5595.453    stream] -- Destroying workers pool JPEG ...
-- DEBUG [5595.453      jw-0] -- Bye-bye (worker jw-0)
-- DEBUG [5595.453    stream] -- Calling ioctl(VIDIOC_STREAMOFF) ...
-- INFO  [5595.455    stream] -- Capturing stopped
-- DEBUG [5595.455    stream] -- Releasing device buffers ...
-- DEBUG [5595.455    stream] -- Closing device ...
-- INFO  [5595.456    stream] -- Device fd=8 closed

and so on. Any ideas?

[device_first_unit.txt](https://github.com/pikvm/ustreamer/files/6137239/device_first_unit.txt)
[device_second_unit.txt](https://github.com/pikvm/ustreamer/files/6137241/device_second_unit.txt)

**Comment by mdevaev** [comment] 2021-03-14 18:04
I think I've seen it somewhere before. This is a driver bug. It. cannot be fixed on the ustreamer side.

**Comment by oh6fub** [comment] 2021-03-14 18:35
Hmm, all right, I will see if something can be done about it... Creative doesn't publish any drivers as the camera should be uvc compatible. I'll post my findings.

**Comment by mdevaev** [comment] 2021-05-30 12:26
What's up?

**Comment by djkraven** [comment] 2021-06-15 22:44
I am getting something similar using a Pi 4 with two USB webcam attached. The same setup on a Pi 3 works. Initially, on the Pi4, both cameras were working but not flipped for the page/port I want them to use. After several attempts to get the systemctl service flipped I was able to get the one cam on the page it belonged on but then the second started failing.

` /usr/bin/ustreamer --process-name-prefix ustreamer-2 --log-level 3 --device /dev/video2 --device-timeout=10  --quality  40 --resolution 1280x720  --desired-fps=29 --host=0.0.0.0 --port=8089 --static /var/www/html/ustreamer-2/ -I USERPTR --format MJPEG
-- INFO  [30966.215      main] -- Using internal blank placeholder
-- DEBUG [30966.215      main] -- Installing SIGINT handler ...
-- DEBUG [30966.215      main] -- Installing SIGTERM handler ...
-- DEBUG [30966.215      main] -- Ignoring SIGPIPE ...
-- INFO  [30966.216      main] -- Enabling HTTP file server: /var/www/html/ustreamer-2/
-- DEBUG [30966.216      main] -- Binding HTTP to [0.0.0.0]:60809 ...
-- INFO  [30966.216      main] -- Listening HTTP on [0.0.0.0]:60809
-- INFO  [30966.217    stream] -- Using V4L2 device: /dev/video2
-- INFO  [30966.217    stream] -- Using desired FPS: 29
-- DEBUG [30966.217    stream] -- _stream_init_loop: stream->run->stop=0
-- INFO  [30966.217      http] -- Starting HTTP eventloop ...
================================================================================
-- DEBUG [30966.235      http] -- HTTP: Updating exposed frame (online=0) ...
-- VERB  [30966.235      http] -- HTTP: Exposed frame: online=0, exp_time=0.000000
-- INFO  [30966.311    stream] -- Device fd=8 opened
-- DEBUG [30966.311    stream] -- Calling ioctl(VIDIOC_QUERYCAP) ...
-- INFO  [30966.311    stream] -- Using input channel: 0
-- DEBUG [30966.311    stream] -- Using TV standard: DEFAULT
-- DEBUG [30966.311    stream] -- Calling ioctl(VIDIOC_S_FMT) ...
-- INFO  [30966.327    stream] -- Using resolution: 1280x720
-- INFO  [30966.327    stream] -- Using pixelformat: MJPEG
-- DEBUG [30966.327    stream] -- Calling ioctl(VIDIOC_G_PARM) ...
-- INFO  [30966.344    stream] -- Using HW FPS: 29 -> 30 (coerced)
-- ERROR [30966.344    stream] -- Device does not support setting of HW encoding quality parameters
-- INFO  [30966.344    stream] -- Using IO method: USERPTR
-- DEBUG [30966.344    stream] -- Calling ioctl(VIDIOC_REQBUFS) for V4L2_MEMORY_USERPTR ...
-- INFO  [30966.344    stream] -- Requested 5 device buffers, got 5
-- DEBUG [30966.344    stream] -- Allocating device buffers ...
-- DEBUG [30966.370    stream] -- Calling ioctl(VIDIOC_QBUF) for buffer 0 ...
-- DEBUG [30966.372    stream] -- Calling ioctl(VIDIOC_QBUF) for buffer 1 ...
-- DEBUG [30966.373    stream] -- Calling ioctl(VIDIOC_QBUF) for buffer 2 ...
-- DEBUG [30966.374    stream] -- Calling ioctl(VIDIOC_QBUF) for buffer 3 ...
-- DEBUG [30966.375    stream] -- Calling ioctl(VIDIOC_QBUF) for buffer 4 ...
-- DEBUG [30966.377    stream] -- Device fd=8 initialized
-- DEBUG [30966.377    stream] -- Calling ioctl(VIDIOC_STREAMON) ...
-- INFO  [30966.385    stream] -- Capturing started
-- INFO  [30966.385    stream] -- Switching to HW encoder: the input is (M)JPEG ...
-- INFO  [30966.385    stream] -- Using JPEG quality: encoder default
-- INFO  [30966.385    stream] -- Creating pool JPEG with 1 workers ...
-- INFO  [30966.385    stream] -- Capturing ...
-- DEBUG [30966.385      jw-0] -- Hello! I am a worker jw-0 ^_^
-- DEBUG [30966.385      jw-0] -- Worker jw-0 waiting for a new job ...
--------------------------------------------------------------------------------
-- DEBUG [30966.386    stream] -- Waiting for worker ...
-- DEBUG [30966.386    stream] -- Calling select() on video device ...
-- DEBUG [30966.451    stream] -- Device select() --> 1
-- DEBUG [30966.451    stream] -- Frame is ready
-- DEBUG [30966.451    stream] -- Grabbing device buffer ...
-- DEBUG [30966.451    stream] -- Grabbed new frame in device buffer: index=0, bytesused=0
-- DEBUG [30966.451    stream] -- Dropped too small frame sized 0 bytes, assuming it was broken
-- DEBUG [30966.451    stream] -- Releasing device buffer index=0 (broken frame) ...
--------------------------------------------------------------------------------
-- DEBUG [30966.452    stream] -- Waiting for worker ...
-- DEBUG [30966.452    stream] -- Calling select() on video device ...
-- DEBUG [30966.452    stream] -- Device select() --> 1
-- DEBUG [30966.452    stream] -- Frame is ready
-- DEBUG [30966.452    stream] -- Grabbing device buffer ...
-- DEBUG [30966.452    stream] -- Grabbed new frame in device buffer: index=1, bytesused=0
-- DEBUG [30966.452    stream] -- Dropped too small frame sized 0 bytes, assuming it was broken
-- DEBUG [30966.452    stream] -- Releasing device buffer index=1 (broken frame) ...
--------------------------------------------------------------------------------
-- DEBUG [30966.453    stream] -- Waiting for worker ...
-- DEBUG [30966.453    stream] -- Calling select() on video device ...
-- DEBUG [30966.453    stream] -- Device select() --> 1
-- DEBUG [30966.453    stream] -- Frame is ready
-- DEBUG [30966.453    stream] -- Grabbing device buffer ...
-- DEBUG [30966.453    stream] -- Grabbed new frame in device buffer: index=2, bytesused=0
-- DEBUG [30966.453    stream] -- Dropped too small frame sized 0 bytes, assuming it was broken
-- DEBUG [30966.453    stream] -- Releasing device buffer index=2 (broken frame) ...
--------------------------------------------------------------------------------
-- DEBUG [30966.453    stream] -- Waiting for worker ...
-- DEBUG [30966.453    stream] -- Calling select() on video device ...
-- DEBUG [30966.454    stream] -- Device select() --> 1
-- DEBUG [30966.454    stream] -- Frame is ready
-- DEBUG [30966.454    stream] -- Grabbing device buffer ...
-- DEBUG [30966.454    stream] -- Grabbed new frame in device buffer: index=3, bytesused=0
-- DEBUG [30966.454    stream] -- Dropped too small frame sized 0 bytes, assuming it was broken
-- DEBUG [30966.454    stream] -- Releasing device buffer index=3 (broken frame) ...
--------------------------------------------------------------------------------
-- DEBUG [30966.454    stream] -- Waiting for worker ...
-- DEBUG [30966.454    stream] -- Calling select() on video device ...
-- DEBUG [30966.454    stream] -- Device select() --> 1
-- DEBUG [30966.454    stream] -- Frame is ready
-- DEBUG [30966.454    stream] -- Grabbing device buffer ...
-- DEBUG [30966.454    stream] -- Grabbed new frame in device buffer: index=4, bytesused=0
-- DEBUG [30966.455    stream] -- Dropped too small frame sized 0 bytes, assuming it was broken
-- DEBUG [30966.455    stream] -- Releasing device buffer index=4 (broken frame) ...
--------------------------------------------------------------------------------
-- DEBUG [30966.455    stream] -- Waiting for worker ...
-- DEBUG [30966.455    stream] -- Calling select() on video device ...
-- DEBUG [30966.547    stream] -- Device select() --> 1
-- DEBUG [30966.547    stream] -- Frame is ready
-- DEBUG [30966.547    stream] -- Grabbing device buffer ...
-- DEBUG [30966.547    stream] -- Grabbed new frame in device buffer: index=0, bytesused=0
-- DEBUG [30966.547    stream] -- Dropped too small frame sized 0 bytes, assuming it was broken
-- DEBUG [30966.547    stream] -- Releasing device buffer index=0 (broken frame) ...
--------------------------------------------------------------------------------
-- DEBUG [30966.547    stream] -- Waiting for worker ...
-- DEBUG [30966.547    stream] -- Calling select() on video device ...
-- DEBUG [30966.547    stream] -- Device select() --> 1
-- DEBUG [30966.548    stream] -- Frame is ready
-- DEBUG [30966.548    stream] -- Grabbing device buffer ...
-- DEBUG [30966.548    stream] -- Grabbed new frame in device buffer: index=1, bytesused=0
-- DEBUG [30966.548    stream] -- Dropped too small frame sized 0 bytes, assuming it was broken
-- DEBUG [30966.548    stream] -- Releasing device buffer index=1 (broken frame) ...
--------------------------------------------------------------------------------
-- DEBUG [30966.548    stream] -- Waiting for worker ...
-- DEBUG [30966.548    stream] -- Calling select() on video device ...
-- DEBUG [30966.548    stream] -- Device select() --> 1
-- DEBUG [30966.548    stream] -- Frame is ready
-- DEBUG [30966.548    stream] -- Grabbing device buffer ...
-- DEBUG [30966.548    stream] -- Grabbed new frame in device buffer: index=2, bytesused=0
-- DEBUG [30966.548    stream] -- Dropped too small frame sized 0 bytes, assuming it was broken
-- DEBUG [30966.549    stream] -- Releasing device buffer index=2 (broken frame) ...
--------------------------------------------------------------------------------
-- DEBUG [30966.549    stream] -- Waiting for worker ...
-- DEBUG [30966.549    stream] -- Calling select() on video device ...
-- DEBUG [30966.549    stream] -- Device select() --> 1
-- DEBUG [30966.549    stream] -- Frame is ready
-- DEBUG [30966.549    stream] -- Grabbing device buffer ...
-- DEBUG [30966.549    stream] -- Grabbed new frame in device buffer: index=3, bytesused=0
-- DEBUG [30966.549    stream] -- Dropped too small frame sized 0 bytes, assuming it was broken
-- DEBUG [30966.549    stream] -- Releasing device buffer index=3 (broken frame) ...
--------------------------------------------------------------------------------
-- DEBUG [30966.550    stream] -- Waiting for worker ...
-- DEBUG [30966.550    stream] -- Calling select() on video device ...
-- DEBUG [30966.550    stream] -- Device select() --> 1
-- DEBUG [30966.551    stream] -- Frame is ready
-- DEBUG [30966.551    stream] -- Grabbing device buffer ...
-- DEBUG [30966.551    stream] -- Grabbed new frame in device buffer: index=4, bytesused=0
-- DEBUG [30966.551    stream] -- Dropped too small frame sized 0 bytes, assuming it was broken
-- DEBUG [30966.551    stream] -- Releasing device buffer index=4 (broken frame) ...
--------------------------------------------------------------------------------
-- DEBUG [30966.551    stream] -- Waiting for worker ...
-- DEBUG [30966.551    stream] -- Calling select() on video device ...
-- DEBUG [30966.563    stream] -- Device select() --> 1
-- DEBUG [30966.563    stream] -- Frame is ready
-- DEBUG [30966.563    stream] -- Grabbing device buffer ...
-- DEBUG [30966.563    stream] -- Grabbed new frame in device buffer: index=0, bytesused=0
-- DEBUG [30966.563    stream] -- Dropped too small frame sized 0 bytes, assuming it was broken
-- DEBUG [30966.563    stream] -- Releasing device buffer index=0 (broken frame) ...
--------------------------------------------------------------------------------
-- DEBUG [30966.563    stream] -- Waiting for worker ...
-- DEBUG [30966.563    stream] -- Calling select() on video device ...
-- DEBUG [30966.563    stream] -- Device select() --> 1
-- DEBUG [30966.563    stream] -- Frame is ready
-- DEBUG [30966.563    stream] -- Grabbing device buffer ...
-- DEBUG [30966.563    stream] -- Grabbed new frame in device buffer: index=1, bytesused=0
-- DEBUG [30966.564    stream] -- Dropped too small frame sized 0 bytes, assuming it was broken
-- DEBUG [30966.564    stream] -- Releasing device buffer index=1 (broken frame) ...
--------------------------------------------------------------------------------
-- DEBUG [30966.564    stream] -- Waiting for worker ...
-- DEBUG [30966.564    stream] -- Calling select() on video device ...
-- DEBUG [30966.564    stream] -- Device select() --> 1
-- DEBUG [30966.564    stream] -- Frame is ready
-- DEBUG [30966.564    stream] -- Grabbing device buffer ...
-- DEBUG [30966.564    stream] -- Grabbed new frame in device buffer: index=2, bytesused=0
-- DEBUG [30966.564    stream] -- Dropped too small frame sized 0 bytes, assuming it was broken
-- DEBUG [30966.564    stream] -- Releasing device buffer index=2 (broken frame) ...
--------------------------------------------------------------------------------
-- DEBUG [30966.565    stream] -- Waiting for worker ...
-- DEBUG [30966.565    stream] -- Calling select() on video device ...
-- DEBUG [30966.565    stream] -- Device select() --> 1
-- DEBUG [30966.565    stream] -- Frame is ready
-- DEBUG [30966.565    stream] -- Grabbing device buffer ...
-- DEBUG [30966.565    stream] -- Grabbed new frame in device buffer: index=3, bytesused=0
-- DEBUG [30966.565    stream] -- Dropped too small frame sized 0 bytes, assuming it was broken
-- DEBUG [30966.565    stream] -- Releasing device buffer index=3 (broken frame) ...
--------------------------------------------------------------------------------
-- DEBUG [30966.566    stream] -- Waiting for worker ...
-- DEBUG [30966.566    stream] -- Calling select() on video device ...
-- DEBUG [30966.566    stream] -- Device select() --> 1
-- DEBUG [30966.566    stream] -- Frame is ready
-- DEBUG [30966.566    stream] -- Grabbing device buffer ...
-- DEBUG [30966.566    stream] -- Grabbed new frame in device buffer: index=4, bytesused=0
-- DEBUG [30966.566    stream] -- Dropped too small frame sized 0 bytes, assuming it was broken
-- DEBUG [30966.566    stream] -- Releasing device buffer index=4 (broken frame) ...
--------------------------------------------------------------------------------
-- DEBUG [30966.566    stream] -- Waiting for worker ...
-- DEBUG [30966.566    stream] -- Calling select() on video device ...
-- DEBUG [30966.611    stream] -- Device select() --> 1
-- DEBUG [30966.611    stream] -- Frame is ready
-- DEBUG [30966.611    stream] -- Grabbing device buffer ...
-- DEBUG [30966.611    stream] -- Grabbed new frame in device buffer: index=0, bytesused=0
-- DEBUG [30966.611    stream] -- Dropped too small frame sized 0 bytes, assuming it was broken
-- DEBUG [30966.611    stream] -- Releasing device buffer index=0 (broken frame) ...
--------------------------------------------------------------------------------
-- DEBUG [30966.612    stream] -- Waiting for worker ...
-- DEBUG [30966.612    stream] -- Calling select() on video device ...
-- DEBUG [30966.612    stream] -- Device select() --> 1
-- DEBUG [30966.612    stream] -- Frame is ready
-- DEBUG [30966.612    stream] -- Grabbing device buffer ...
-- DEBUG [30966.612    stream] -- Grabbed new frame in device buffer: index=1, bytesused=0
-- DEBUG [30966.612    stream] -- Dropped too small frame sized 0 bytes, assuming it was broken
-- DEBUG [30966.612    stream] -- Releasing device buffer index=1 (broken frame) ...
--------------------------------------------------------------------------------
-- DEBUG [30966.613    stream] -- Waiting for worker ...
-- DEBUG [30966.613    stream] -- Calling select() on video device ...
-- DEBUG [30966.613    stream] -- Device select() --> 1
-- DEBUG [30966.613    stream] -- Frame is ready
-- DEBUG [30966.613    stream] -- Grabbing device buffer ...
-- DEBUG [30966.613    stream] -- Grabbed new frame in device buffer: index=2, bytesused=0
-- DEBUG [30966.613    stream] -- Dropped too small frame sized 0 bytes, assuming it was broken
-- DEBUG [30966.613    stream] -- Releasing device buffer index=2 (broken frame) ...
--------------------------------------------------------------------------------
-- DEBUG [30966.614    stream] -- Waiting for worker ...
-- DEBUG [30966.614    stream] -- Calling select() on video device ...
-- DEBUG [30966.614    stream] -- Device select() --> 1
-- DEBUG [30966.614    stream] -- Frame is ready
-- DEBUG [30966.614    stream] -- Grabbing device buffer ...
-- DEBUG [30966.615    stream] -- Grabbed new frame in device buffer: index=3, bytesused=0
-- DEBUG [30966.615    stream] -- Dropped too small frame sized 0 bytes, assuming it was broken
-- DEBUG [30966.615    stream] -- Releasing device buffer index=3 (broken frame) ...
--------------------------------------------------------------------------------
-- DEBUG [30966.615    stream] -- Waiting for worker ...
-- DEBUG [30966.615    stream] -- Calling select() on video device ...
-- DEBUG [30966.616    stream] -- Device select() --> 1
-- DEBUG [30966.616    stream] -- Frame is ready
-- DEBUG [30966.616    stream] -- Grabbing device buffer ...
-- DEBUG [30966.616    stream] -- Grabbed new frame in device buffer: index=4, bytesused=0
-- DEBUG [30966.616    stream] -- Dropped too small frame sized 0 bytes, assuming it was broken
-- DEBUG [30966.616    stream] -- Releasing device buffer index=4 (broken frame) ...
--------------------------------------------------------------------------------
-- DEBUG [30966.617    stream] -- Waiting for worker ...
-- DEBUG [30966.617    stream] -- Calling select() on video device ...
-- DEBUG [30966.722    stream] -- Device select() --> 1
-- DEBUG [30966.722    stream] -- Frame is ready
-- DEBUG [30966.722    stream] -- Grabbing device buffer ...
-- DEBUG [30966.722    stream] -- Grabbed new frame in device buffer: index=0, bytesused=0
-- DEBUG [30966.722    stream] -- Dropped too small frame sized 0 bytes, assuming it was broken
-- DEBUG [30966.722    stream] -- Releasing device buffer index=0 (broken frame) ...
--------------------------------------------------------------------------------
-- DEBUG [30966.723    stream] -- Waiting for worker ...
-- DEBUG [30966.723    stream] -- Calling select() on video device ...
-- DEBUG [30966.723    stream] -- Device select() --> 1
-- DEBUG [30966.723    stream] -- Frame is ready
-- DEBUG [30966.723    stream] -- Grabbing device buffer ...
-- DEBUG [30966.723    stream] -- Grabbed new frame in device buffer: index=1, bytesused=0
-- DEBUG [30966.723    stream] -- Dropped too small frame sized 0 bytes, assuming it was broken
-- DEBUG [30966.723    stream] -- Releasing device buffer index=1 (broken frame) ...
--------------------------------------------------------------------------------
-- DEBUG [30966.724    stream] -- Waiting for worker ...
-- DEBUG [30966.724    stream] -- Calling select() on video device ...
-- DEBUG [30966.724    stream] -- Device select() --> 1
-- DEBUG [30966.724    stream] -- Frame is ready
-- DEBUG [30966.724    stream] -- Grabbing device buffer ...
-- DEBUG [30966.724    stream] -- Grabbed new frame in device buffer: index=2, bytesused=0
-- DEBUG [30966.724    stream] -- Dropped too small frame sized 0 bytes, assuming it was broken
-- DEBUG [30966.724    stream] -- Releasing device buffer index=2 (broken frame) ...
--------------------------------------------------------------------------------
-- DEBUG [30966.725    stream] -- Waiting for worker ...
-- DEBUG [30966.725    stream] -- Calling select() on video device ...
-- DEBUG [30966.725    stream] -- Device select() --> 1
-- DEBUG [30966.725    stream] -- Frame is ready
-- DEBUG [30966.725    stream] -- Grabbing device buffer ...
-- DEBUG [30966.725    stream] -- Grabbed new frame in device buffer: index=3, bytesused=0
-- DEBUG [30966.725    stream] -- Dropped too small frame sized 0 bytes, assuming it was broken
-- DEBUG [30966.725    stream] -- Releasing device buffer index=3 (broken frame) ...
--------------------------------------------------------------------------------
-- DEBUG [30966.725    stream] -- Waiting for worker ...
-- DEBUG [30966.726    stream] -- Calling select() on video device ...
-- DEBUG [30966.726    stream] -- Device select() --> 1
-- DEBUG [30966.726    stream] -- Frame is ready
-- DEBUG [30966.726    stream] -- Grabbing device buffer ...
-- DEBUG [30966.726    stream] -- Grabbed new frame in device buffer: index=4, bytesused=0
-- DEBUG [30966.726    stream] -- Dropped too small frame sized 0 bytes, assuming it was broken
-- DEBUG [30966.726    stream] -- Releasing device buffer index=4 (broken frame) ...
--------------------------------------------------------------------------------
-- DEBUG [30966.726    stream] -- Waiting for worker ...
-- DEBUG [30966.726    stream] -- Calling select() on video device ...
-- DEBUG [30967.237      http] -- HTTP: Repeating exposed ...
-- DEBUG [30968.250      http] -- HTTP: Repeating exposed ...
-- DEBUG [30969.252      http] -- HTTP: Repeating exposed ...
-- DEBUG [30970.270      http] -- HTTP: Repeating exposed ...
-- DEBUG [30971.271      http] -- HTTP: Repeating exposed ...
-- DEBUG [30972.280      http] -- HTTP: Repeating exposed ...
-- DEBUG [30973.289      http] -- HTTP: Repeating exposed ...
-- DEBUG [30974.304      http] -- HTTP: Repeating exposed ...
-- DEBUG [30975.306      http] -- HTTP: Repeating exposed ...
-- VERB  [30975.673      http] -- HTTP: Requested static path /var/www/html/ustreamer-2/// is a directory, trying /var/www/html/ustreamer-2////index.html
-- INFO  [30975.827      http] -- HTTP: Registered client: [192.168.1.1]:65396, id=548d83602630aa59; clients now: 1
-- DEBUG [30976.323      http] -- HTTP: Repeating exposed ...
-- DEBUG [30976.730    stream] -- Device select() --> 0
-- ERROR [30976.730    stream] -- Mainloop select() error: Inappropriate ioctl for device
-- INFO  [30976.730    stream] -- Destroying workers pool JPEG ...
-- DEBUG [30976.730      jw-0] -- Bye-bye (worker jw-0)
-- DEBUG [30976.731    stream] -- Calling ioctl(VIDIOC_STREAMOFF) ...
-- INFO  [30976.736    stream] -- Capturing stopped
-- DEBUG [30976.737    stream] -- Releasing device buffers ...
-- DEBUG [30976.737    stream] -- Closing device ...
-- INFO  [30976.744    stream] -- Device fd=8 closed
-- DEBUG [30976.745    stream] -- _stream_init_loop: stream->run->stop=0
================================================================================
-- INFO  [30976.752    stream] -- Device fd=8 opened
-- DEBUG [30976.752    stream] -- Calling ioctl(VIDIOC_QUERYCAP) ...
-- INFO  [30976.753    stream] -- Using input channel: 0
-- DEBUG [30976.753    stream] -- Using TV standard: DEFAULT
-- DEBUG [30976.753    stream] -- Calling ioctl(VIDIOC_S_FMT) ...
-- DEBUG [30976.754      http] -- HTTP: Updating exposed frame (online=0) ...
-- VERB  [30976.754      http] -- HTTP: Exposed frame: online=0, exp_time=0.000000
-- INFO  [30977.342    stream] -- Using resolution: 1280x720
-- INFO  [30977.342    stream] -- Using pixelformat: MJPEG
-- DEBUG [30977.343    stream] -- Calling ioctl(VIDIOC_G_PARM) ...
-- INFO  [30977.359    stream] -- Using HW FPS: 29 -> 30 (coerced)
-- ERROR [30977.359    stream] -- Device does not support setting of HW encoding quality parameters
-- INFO  [30977.359    stream] -- Using IO method: USERPTR
-- DEBUG [30977.359    stream] -- Calling ioctl(VIDIOC_REQBUFS) for V4L2_MEMORY_USERPTR ...
-- INFO  [30977.359    stream] -- Requested 5 device buffers, got 5
-- DEBUG [30977.359    stream] -- Allocating device buffers ...
-- DEBUG [30977.384    stream] -- Calling ioctl(VIDIOC_QBUF) for buffer 0 ...
-- DEBUG [30977.386    stream] -- Calling ioctl(VIDIOC_QBUF) for buffer 1 ...
-- DEBUG [30977.387    stream] -- Calling ioctl(VIDIOC_QBUF) for buffer 2 ...
-- DEBUG [30977.389    stream] -- Calling ioctl(VIDIOC_QBUF) for buffer 3 ...
-- DEBUG [30977.390    stream] -- Calling ioctl(VIDIOC_QBUF) for buffer 4 ...
-- DEBUG [30977.392    stream] -- Device fd=8 initialized
-- DEBUG [30977.392    stream] -- Calling ioctl(VIDIOC_STREAMON) ...
-- INFO  [30977.400    stream] -- Capturing started
-- INFO  [30977.400    stream] -- Switching to HW encoder: the input is (M)JPEG ...
-- INFO  [30977.401    stream] -- Using JPEG quality: encoder default
-- INFO  [30977.401    stream] -- Creating pool JPEG with 1 workers ...
-- INFO  [30977.401    stream] -- Capturing ...
--------------------------------------------------------------------------------
-- DEBUG [30977.408    stream] -- Waiting for worker ...
-- DEBUG [30977.408    stream] -- Calling select() on video device ...
-- DEBUG [30977.409      jw-0] -- Hello! I am a worker jw-0 ^_^
-- DEBUG [30977.409      jw-0] -- Worker jw-0 waiting for a new job ...
-- DEBUG [30977.457    stream] -- Device select() --> 1
-- DEBUG [30977.457    stream] -- Frame is ready
-- DEBUG [30977.457    stream] -- Grabbing device buffer ...
-- DEBUG [30977.457    stream] -- Grabbed new frame in device buffer: index=0, bytesused=0
-- DEBUG [30977.457    stream] -- Dropped too small frame sized 0 bytes, assuming it was broken
-- DEBUG [30977.457    stream] -- Releasing device buffer index=0 (broken frame) ...
--------------------------------------------------------------------------------
-- DEBUG [30977.458    stream] -- Waiting for worker ...
-- DEBUG [30977.458    stream] -- Calling select() on video device ...
-- DEBUG [30977.458    stream] -- Device select() --> 1
-- DEBUG [30977.458    stream] -- Frame is ready
-- DEBUG [30977.458    stream] -- Grabbing device buffer ...
-- DEBUG [30977.458    stream] -- Grabbed new frame in device buffer: index=1, bytesused=0
-- DEBUG [30977.458    stream] -- Dropped too small frame sized 0 bytes, assuming it was broken
-- DEBUG [30977.458    stream] -- Releasing device buffer index=1 (broken frame) ...
--------------------------------------------------------------------------------
-- DEBUG [30977.459    stream] -- Waiting for worker ...
-- DEBUG [30977.459    stream] -- Calling select() on video device ...
-- DEBUG [30977.459    stream] -- Device select() --> 1
-- DEBUG [30977.459    stream] -- Frame is ready
-- DEBUG [30977.459    stream] -- Grabbing device buffer ...
-- DEBUG [30977.459    stream] -- Grabbed new frame in device buffer: index=2, bytesused=0
-- DEBUG [30977.459    stream] -- Dropped too small frame sized 0 bytes, assuming it was broken
-- DEBUG [30977.460    stream] -- Releasing device buffer index=2 (broken frame) ...
--------------------------------------------------------------------------------
`

**Comment by djkraven** [comment] 2021-06-17 13:19
I have success getting both webcams to run. It appears the issue may be related to the USB hub on the Pi4. After trying a different combination of which port they were plugged into the second finally came on. It was stable for a while yesterday then it went to No Imagine. I have updated the EEPROM to the latest this morning and will see if that improves the issue. The failing camera would disappear from the lsusb listing which lead to looking into the USB hub.

**Comment by mdevaev** [comment] 2021-07-04 12:07
Okay, I think the problem is solved here.

**Closed by mdevaev** 2021-07-04 12:07 UTC
Labels: type:question
